<?php
//require('../includes/header.php');
echo'
<br>
<div class="limitpays">
<table class="tablediapo">
<tr>
<td class="tdcouleur1">
aa </td><td class="tdcouleur1"> Afar                    </td></tr><td class="tdcouleur1">
ab </td><td class="tdcouleur1"> Abkhazie                </td></tr><td class="tdcouleur1">
af </td><td class="tdcouleur1"> Afrikaner               </td></tr><td class="tdcouleur1">
am </td><td class="tdcouleur1"> Amhara                  </td></tr><td class="tdcouleur1">
ar </td><td class="tdcouleur1"> Arabie                  </td></tr><td class="tdcouleur1">
as </td><td class="tdcouleur1"> Assam                   </td></tr><td class="tdcouleur1">
ay </td><td class="tdcouleur1"> Aymara                  </td></tr><td class="tdcouleur1">
az </td><td class="tdcouleur1"> Azerbaidjan             </td></tr><td class="tdcouleur1">
ba </td><td class="tdcouleur1"> Bachkir                 </td></tr><td class="tdcouleur1">
be </td><td class="tdcouleur1"> Bielorusse              </td></tr><td class="tdcouleur1">
bg </td><td class="tdcouleur1"> Bulgarie                </td></tr><td class="tdcouleur1">
bh </td><td class="tdcouleur1"> Bihari                  </td></tr><td class="tdcouleur1">
bi </td><td class="tdcouleur1"> BÛche de mer            </td></tr><td class="tdcouleur1">
bn </td><td class="tdcouleur1"> Bengali                 </td></tr><td class="tdcouleur1">
bo </td><td class="tdcouleur1"> Tibetain                </td></tr><td class="tdcouleur1">
br </td><td class="tdcouleur1"> Breton                  </td></tr><td class="tdcouleur1">
ca </td><td class="tdcouleur1"> Catalan                  </td></tr><td class="tdcouleur1">
co </td><td class="tdcouleur1"> Corse                   </td></tr><td class="tdcouleur1">
cs </td><td class="tdcouleur1"> Tcheque                 </td></tr><td class="tdcouleur1">
cy </td><td class="tdcouleur1"> Wallis                  </td></tr><td class="tdcouleur1">
da </td><td class="tdcouleur1"> Danois                  </td></tr><td class="tdcouleur1">
de </td><td class="tdcouleur1"> Allemand                </td></tr><td class="tdcouleur1">
dz </td><td class="tdcouleur1"> Dzoungarie-Bhoutan      </td></tr><td class="tdcouleur1">
el </td><td class="tdcouleur1"> Grec                    </td></tr><td class="tdcouleur1">
en </td><td class="tdcouleur1"> Anglais                 </td></tr><td class="tdcouleur1">
eo </td><td class="tdcouleur1"> Esperanto               </td></tr><td class="tdcouleur1">
es </td><td class="tdcouleur1"> Espagnol                </td></tr><td class="tdcouleur1">
et </td><td class="tdcouleur1"> Estonien                </td></tr><td class="tdcouleur1">
eu </td><td class="tdcouleur1"> Basque                  </td></tr><td class="tdcouleur1">
fa </td><td class="tdcouleur1"> Perse                   </td></tr><td class="tdcouleur1">
fi </td><td class="tdcouleur1"> Finlandais              </td></tr><td class="tdcouleur1">
fj </td><td class="tdcouleur1"> Fidji                   </td></tr><td class="tdcouleur1">
fo </td><td class="tdcouleur1"> Feroien                 </td></tr><td class="tdcouleur1">
fr </td><td class="tdcouleur1"> Francais                </td></tr><td class="tdcouleur1">
fy </td><td class="tdcouleur1"> Frison                  </td></tr><td class="tdcouleur1">
ga </td><td class="tdcouleur1"> Irlandais               </td></tr><td class="tdcouleur1">
gd </td><td class="tdcouleur1"> Gallois                 </td></tr><td class="tdcouleur1">
gl </td><td class="tdcouleur1"> Galicien                </td></tr><td class="tdcouleur1">
gn </td><td class="tdcouleur1"> Guarani                 </td></tr><td class="tdcouleur1">
gu </td><td class="tdcouleur1"> Goudjerate              </td></tr><td class="tdcouleur1">
ha </td><td class="tdcouleur1"> Haoussa                 </td></tr><td class="tdcouleur1">
hi </td><td class="tdcouleur1"> Hindi                   </td></tr><td class="tdcouleur1">
hr </td><td class="tdcouleur1"> Croate                  </td></tr><td class="tdcouleur1">
hu </td><td class="tdcouleur1"> Hongrois                </td></tr><td class="tdcouleur1">
hy </td><td class="tdcouleur1"> Armenien                </td></tr><td class="tdcouleur1">
ia </td><td class="tdcouleur1"> Interlingua             </td></tr><td class="tdcouleur1">
id </td><td class="tdcouleur1"> Indonesien              </td></tr><td class="tdcouleur1">
ie </td><td class="tdcouleur1"> Interlingue             </td></tr><td class="tdcouleur1">
ik </td><td class="tdcouleur1"> Iupik                   </td></tr><td class="tdcouleur1">
is </td><td class="tdcouleur1"> Islandais               </td></tr><td class="tdcouleur1">
it </td><td class="tdcouleur1"> Italien                 </td></tr><td class="tdcouleur1">
iu </td><td class="tdcouleur1"> Inupik                  </td></tr><td class="tdcouleur1">
ja </td><td class="tdcouleur1"> Japonais                </td></tr><td class="tdcouleur1">
yi </td><td class="tdcouleur1"> Yiddish                 </td></tr><td class="tdcouleur1">
jv </td><td class="tdcouleur1"> Javanais                </td></tr><td class="tdcouleur1">
ka </td><td class="tdcouleur1"> Georgien                </td></tr><td class="tdcouleur1">
kk </td><td class="tdcouleur1"> Kazakh                  </td></tr><td class="tdcouleur1">
kl </td><td class="tdcouleur1"> Kalaallisut             </td></tr><td class="tdcouleur1">
km </td><td class="tdcouleur1"> Khmer                   </td></tr><td class="tdcouleur1">
kn </td><td class="tdcouleur1"> Kannada                 </td></tr><td class="tdcouleur1">
ko </td><td class="tdcouleur1"> Coreen                  </td></tr><td class="tdcouleur1">
ks </td><td class="tdcouleur1"> Cachemire               </td></tr><td class="tdcouleur1">
ku </td><td class="tdcouleur1"> Kurde                   </td></tr><td class="tdcouleur1">
ky </td><td class="tdcouleur1"> Kirghize                </td></tr><td class="tdcouleur1">
la </td><td class="tdcouleur1"> Latin                   </td></tr><td class="tdcouleur1">
ln </td><td class="tdcouleur1"> Lingala                 </td></tr><td class="tdcouleur1">
lo </td><td class="tdcouleur1"> Laotien                 </td></tr><td class="tdcouleur1">
lt </td><td class="tdcouleur1"> Lituanien               </td></tr><td class="tdcouleur1">
lv </td><td class="tdcouleur1"> Letton                  </td></tr><td class="tdcouleur1">
mg </td><td class="tdcouleur1"> Malgache                </td></tr><td class="tdcouleur1">
mi </td><td class="tdcouleur1"> Maoris                  </td></tr><td class="tdcouleur1">
mk </td><td class="tdcouleur1"> Macedoine               </td></tr><td class="tdcouleur1">
ml </td><td class="tdcouleur1"> Malayalam               </td></tr><td class="tdcouleur1">
mn </td><td class="tdcouleur1"> Mongol                  </td></tr><td class="tdcouleur1">
mo </td><td class="tdcouleur1"> Moldave                 </td></tr><td class="tdcouleur1">
mr </td><td class="tdcouleur1"> Marathe                 </td></tr><td class="tdcouleur1">
ms </td><td class="tdcouleur1"> Malais                  </td></tr><td class="tdcouleur1">
mt </td><td class="tdcouleur1"> Maltais                 </td></tr><td class="tdcouleur1">
my </td><td class="tdcouleur1"> Birman                  </td></tr><td class="tdcouleur1">
na </td><td class="tdcouleur1"> Nauruan                 </td></tr><td class="tdcouleur1">
ne </td><td class="tdcouleur1"> Nepalais                </td></tr><td class="tdcouleur1">
nl </td><td class="tdcouleur1"> Hollandais              </td></tr><td class="tdcouleur1">
no </td><td class="tdcouleur1"> Norvegien               </td></tr><td class="tdcouleur1">
oc </td><td class="tdcouleur1"> Occitan                 </td></tr><td class="tdcouleur1">
om </td><td class="tdcouleur1"> Oromos                  </td></tr><td class="tdcouleur1">
or </td><td class="tdcouleur1"> Oriya                   </td></tr><td class="tdcouleur1">
pa </td><td class="tdcouleur1"> Pendjab                 </td></tr><td class="tdcouleur1">
pl </td><td class="tdcouleur1"> Polonais                </td></tr><td class="tdcouleur1">
ps </td><td class="tdcouleur1"> Pachtoune               </td></tr><td class="tdcouleur1">
pt </td><td class="tdcouleur1"> Portugais               </td></tr><td class="tdcouleur1">
qu </td><td class="tdcouleur1"> Quechua                 </td></tr><td class="tdcouleur1">
rm </td><td class="tdcouleur1"> Rheto-roman             </td></tr><td class="tdcouleur1">
rn </td><td class="tdcouleur1"> Roundi                  </td></tr><td class="tdcouleur1">
ro </td><td class="tdcouleur1"> Roumain                 </td></tr><td class="tdcouleur1">
ru </td><td class="tdcouleur1"> Russe                   </td></tr><td class="tdcouleur1">
rw </td><td class="tdcouleur1"> Kinyarwanda             </td></tr><td class="tdcouleur1">
sa </td><td class="tdcouleur1"> Sanskrit                </td></tr><td class="tdcouleur1">
sd </td><td class="tdcouleur1"> Sindhi                  </td></tr><td class="tdcouleur1">
sg </td><td class="tdcouleur1"> Sango                   </td></tr><td class="tdcouleur1">
sh </td><td class="tdcouleur1"> Serbo-croate            </td></tr><td class="tdcouleur1">
si </td><td class="tdcouleur1"> cinghalais              </td></tr><td class="tdcouleur1">
sk </td><td class="tdcouleur1"> Slovaque                </td></tr><td class="tdcouleur1">
sl </td><td class="tdcouleur1"> Slovene                 </td></tr><td class="tdcouleur1">
sm </td><td class="tdcouleur1"> Samoan                  </td></tr><td class="tdcouleur1">
sn </td><td class="tdcouleur1"> Chona                   </td></tr><td class="tdcouleur1">
so </td><td class="tdcouleur1"> Somali                  </td></tr><td class="tdcouleur1">
sq </td><td class="tdcouleur1"> Albanais                </td></tr><td class="tdcouleur1">
sr </td><td class="tdcouleur1"> Serbe                   </td></tr><td class="tdcouleur1">
ss </td><td class="tdcouleur1"> Siswati                 </td></tr><td class="tdcouleur1">
st </td><td class="tdcouleur1"> SotoduSud               </td></tr><td class="tdcouleur1">
su </td><td class="tdcouleur1"> Soudanais               </td></tr><td class="tdcouleur1">
sv </td><td class="tdcouleur1"> Suedois                 </td></tr><td class="tdcouleur1">
sw </td><td class="tdcouleur1"> Souaheli                </td></tr><td class="tdcouleur1">
ta </td><td class="tdcouleur1"> Tamil                   </td></tr><td class="tdcouleur1">
te </td><td class="tdcouleur1"> Telougou                </td></tr><td class="tdcouleur1">
tg </td><td class="tdcouleur1"> Tadjik                  </td></tr><td class="tdcouleur1">
th </td><td class="tdcouleur1"> Thai                    </td></tr><td class="tdcouleur1">
ti </td><td class="tdcouleur1"> Tigrigna                </td></tr><td class="tdcouleur1">
tk </td><td class="tdcouleur1"> Turkmene                </td></tr><td class="tdcouleur1">
tl </td><td class="tdcouleur1"> Tagal                   </td></tr><td class="tdcouleur1">
tn </td><td class="tdcouleur1"> Setchwana               </td></tr><td class="tdcouleur1">
to </td><td class="tdcouleur1"> Kitonga                 </td></tr><td class="tdcouleur1">
tr </td><td class="tdcouleur1"> Turc                    </td></tr><td class="tdcouleur1">
ts </td><td class="tdcouleur1"> Tsonga                  </td></tr><td class="tdcouleur1">
tt </td><td class="tdcouleur1"> Tatar                   </td></tr><td class="tdcouleur1">
tw </td><td class="tdcouleur1"> Tchi                    </td></tr><td class="tdcouleur1">
ug </td><td class="tdcouleur1"> Uigur                   </td></tr><td class="tdcouleur1">
uk </td><td class="tdcouleur1"> Ukrainien               </td></tr><td class="tdcouleur1">
ur </td><td class="tdcouleur1"> Ourdou                  </td></tr><td class="tdcouleur1">
uz </td><td class="tdcouleur1"> Ouzbek                  </td></tr><td class="tdcouleur1">
vi </td><td class="tdcouleur1"> Vietnamien              </td></tr><td class="tdcouleur1">
vo </td><td class="tdcouleur1"> Volap³k                 </td></tr><td class="tdcouleur1">
wo </td><td class="tdcouleur1"> Ouolof                  </td></tr><td class="tdcouleur1">
xh </td><td class="tdcouleur1"> Xhosa                   </td></tr><td class="tdcouleur1">
yi </td><td class="tdcouleur1"> Yiddish                 </td></tr><td class="tdcouleur1">
yo </td><td class="tdcouleur1"> Yorouba                 </td></tr><td class="tdcouleur1">
za </td><td class="tdcouleur1"> Zhuangzi                </td></tr><td class="tdcouleur1">
zh </td><td class="tdcouleur1"> Chinois                 </td></tr><td class="tdcouleur1">
zu </td><td class="tdcouleur1"> Zoulou                  </td></tr></table>
</div>
';
?>